[package]
name = "json-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
json = "0.12.4"
oxrdf = { git = "https://github.com/jeswr/oxigraph", rev = "9a04d4e9cb7e98a5ac4829cf37fd22cd7f985ec3" }
oxttl = { git = "https://github.com/jeswr/oxigraph", rev = "9a04d4e9cb7e98a5ac4829cf37fd22cd7f985ec3" }
risc0-zkvm = { version = "1.2.0" }
serde = "1.0"
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
spareval = { git = "https://github.com/jeswr/oxigraph", rev = "9a04d4e9cb7e98a5ac4829cf37fd22cd7f985ec3" }
spargebra = { git = "https://github.com/jeswr/oxigraph", rev = "9a04d4e9cb7e98a5ac4829cf37fd22cd7f985ec3" }
oxsdatatypes = { git = "https://github.com/jeswr/oxigraph", features = ["no-duration-coercion", "custom-now"], rev = "9a04d4e9cb7e98a5ac4829cf37fd22cd7f985ec3" }
