name: Rust CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -L https://risczero.com/install | bash
        shell: bash
      - run: source "/home/runner/.bashrc"
        shell: bash
      - run: rzup install
        shell: bash
      - run: cargo run --release
        shell: bash
