name: Rust CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rzup
        run: |
          curl -L https://risczero.com/install | bash
          source "/home/runner/.bashrc"
          /home/runner/.risc0/bin install
        shell: bash
      - run: cargo run --release
        shell: bash
